version: '3.8'
services:
  app:
    build:
      context: .
    container_name: nutrifit-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvis14ogjchc73bvocn0-a.oregon-postgres.render.com:5432/nutrifit_g7ml
      SPRING_DATASOURCE_USERNAME: nutrifit_g7ml_user
      SPRING_DATASOURCE_PASSWORD: rchjjNjafmPptMRm78kDKU9Hai5v7syI
    ports:
      - "8080:8080"

volumes:
  mysql-data: