version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nutrifit
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: nutrifit-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nutrifit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: