spring:
  datasource:
    url: jdbc:postgresql://dpg-cvis14ogjchc73bvocn0-a.oregon-postgres.render.com:5432/nutrifit_g7ml
    username: nutrifit_g7ml_user
    password: rchjjNjafmPptMRm78kDKU9Hai5v7syI
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  token:
    validity: 7200000
    refresh: 2592000000
    prefix: Bearer
  signing:
    key: nutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifitnutrifit
  authorities:
    key: roles
  header:
    string: Authorization






